# Generated by Django 4.1.3 on 2023-08-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="end_date",
            field=models.DateTimeField(null=True, verbose_name="date ended"),
        ),
    ]
