# Generated by Django 4.1.3 on 2023-09-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_question_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="available",
            field=models.BooleanField(default=True,
                                      verbose_name="poll available"),
        ),
    ]
