# Generated by Django 4.1.3 on 2023-09-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_question_available"),
        ("polls", "0004_remove_choice_votes_alter_vote_question_and_more"),
    ]

    operations = []
