# Generated by Django 4.1.3 on 2023-09-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_alter_question_pub_date"),
        ("polls", "0005_merge_20230906_1457"),
    ]

    operations = []
